#spring.datasource.jdbcUrl=jdbc:mysql://localhost:3308/spring_batch
#spring.datasource.username=root
#spring.datasource.password=root
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
#spring.batch.jdbc.initialize-schema=always
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.hibernate.ddl-auto=none

chunkSize: 10
pageSize: 10

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3307/spring_batch
    username: root
    password: 1234567
  batch:
    jdbc:
      initialize-schema: always
app:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3307/app
    username: root
    password: 1234567